# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  workflow_dispatch:

env:
  CI_DIR: 4965b481-b108-4ecd-a720-19c26f7b936b

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          targets: |
            x86_64-unknown-linux-gnu
            x86_64-unknown-linux-musl
            x86_64-pc-windows-gnu
            x86_64-apple-darwin
            aarch64-apple-darwin
            aarch64-unknown-linux-gnu
            aarch64-unknown-linux-musl

      - name: Create tarball
        env:
          BUILD_ARTIFACTS: ${{ join(fromJSON(steps.build.outputs.artifacts).*, fromJSON('"\n"')) }}
        run: |
          set -Eeuo pipefail
          readarray -t artifacts <<< "$BUILD_ARTIFACTS"
          mkdir -p "$CI_DIR"
          tar -czf "$CI_DIR/build.tar.gz" "${artifacts[@]}"

      - name: Upload tarball
        uses: actions/upload-artifact@1eb3cb2b3e0f29609092a73eb033bb759a334595 # v4.1.0
        with:
          name: build
          path: ${{ env.CI_DIR }}/build.tar.gz
