# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  workflow_dispatch:

env:
  CI_DIR: 4965b481-b108-4ecd-a720-19c26f7b936b

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          targets: |
            x86_64-unknown-linux-gnu
            x86_64-unknown-linux-musl
            x86_64-pc-windows-gnu
            x86_64-apple-darwin
            aarch64-apple-darwin
            aarch64-unknown-linux-gnu
            aarch64-unknown-linux-musl

      - name: Create tarball
        env:
          BUILD_ARTIFACTS: ${{ join(fromJSON(steps.build.outputs.artifacts).*, fromJSON('"\n"')) }}
        run: |
          set -Eeuo pipefail
          readarray -t artifacts <<< "$BUILD_ARTIFACTS"
          mkdir -p "$CI_DIR"
          tar -czf "$CI_DIR/build.tar.gz" "${artifacts[@]}"

      - name: Upload tarball
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: build
          path: ${{ env.CI_DIR }}/build.tar.gz
